### ISSUE TITLE
 responsiveness issue opening the page from my cell phone's safari browser(iOS)

### ISSUE THREAD

**Issue by anbestephen** [raeprojects/www-raeprojects-org#6]

**Comment by anbestephen** [comment]
i think the problem is caused because the images in the 'work that we are proud of' block are not responsive , even thought the navbar and other parts of the page are reponsive these images are causing the issue

**Comment by tsinat** [comment]
I have resolved the issue with the on the portfolio section and I will optimize it further

**Comment by anbestephen** [comment]
the problem is fixed. i am closing this issue now
